# Generated by Django 5.1.3 on 2024-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_yfinance', '0003_stockinfo_stockprice_delete_stockdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='value1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='value2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
